---
abstract: 'Metasploit MSG-RPC Communications Module'
author:
  - 'Ryan Linn <rlinn@trustwave.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-MSFRPC
no_index:
  directory:
    - t
    - inc
requires:
  Data::MessagePack: 0.3
  HTTP::Request: 0
  LWP: 0
  Test::More: 0
version: 0.01
